In [2]:
# Preprocessing on npr dataset 
# www.npr.org
import pandas as pd
npr = pd.read_csv('npr.csv')
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [3]:
len(npr)
print(npr.shape)


(11992, 1)


In [4]:
npr['Article'][1]

'  Donald Trump has used Twitter  —   his preferred means of communication  —   to weigh in on a swath of foreign policy issues over the past few weeks. His comments give a glimpse into how his incoming administration will deal with pressing foreign matters  —   but also highlight how reactionary comments on social media can immediately spur international concern and attention. And his staff has indicated that taking to Twitter to air his concerns or, often, grievances, won’t end once he enters the Oval Office. On Wednesday, Trump blasted the U. S.’s abstention from the U. N. Security Council vote on Israeli settlements earlier this month. The tweets came just hours before Secretary of State John Kerry gave a speech defending the decision and calling the continued building of settlements on Palestinian territory in the West Bank a threat to the   solution in the region. Trump’s support for Israel and Prime Minister Benjamin Netanyahu  —   who has had a fraught relationship with Preside

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
dtm = cv.fit_transform(npr['Article'])
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [7]:
#from sklearn.decomposition import LatentDirichletAllocation
#LDA = LatentDirichletAllocation(n_components=7,random_state=42)
from sklearn.decomposition import NMF
LDA = NMF(n_components=7,random_state=42)
LDA.fit(dtm)

NMF(n_components=7, random_state=42)

# Three Steps Away...
### Grab the vocab.
### Grab the topic
### and finally grab the highest prob. word per topic



In [8]:
len(cv.get_feature_names_out())

54777

In [9]:
type(cv.get_feature_names_out())

numpy.ndarray

In [10]:
cv.get_feature_names_out()[5510]

'beret'

In [11]:
import random

In [12]:
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(cv.get_feature_names_out()[random_word_id])

ambition
expat
behdad
elm
astray
brca
hindenburg
freezing
delivery
fabulously


### Showing Top Words Per Topic

In [13]:
len(LDA.components_)

7

In [14]:
LDA.components_.shape

(7, 54777)

In [15]:
LDA.components_

array([[2.59307648e-02, 0.00000000e+00, 4.98733289e-04, ...,
        1.18791108e-03, 1.20059891e-03, 2.96506230e-03],
       [7.41439887e-03, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 9.53109960e-01, 0.00000000e+00, ...,
        1.73180537e-03, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 7.63497656e-01, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.70655585e-02, 8.13458597e-01, 0.00000000e+00, ...,
        0.00000000e+00, 2.77868834e-04, 0.00000000e+00],
       [0.00000000e+00, 1.62541572e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [16]:
len(LDA.components_[0])

54777

In [17]:
single_topic = LDA.components_[0]

In [18]:
# Returns the indices that would sort this array.
single_topic.argsort()

array([33703, 41834, 41835, ..., 26752, 36283, 28659], dtype=int64)

In [19]:
#lets understand the argsort in simple example
import numpy as np
arr = np.array([10,200,1])
arr.argsort()


array([2, 0, 1], dtype=int64)

In [20]:
# Word least representative of this topic
single_topic[18302]

0.14023542127765248

In [21]:
# Word most representative of this topic
single_topic[42997]

0.0

In [22]:
# Top 10 words for this topic:
single_topic.argsort()[-10:]

array([15008, 53211, 49459, 21073, 39848, 27439, 49183, 26752, 36283,
       28659], dtype=int64)

In [23]:
top_word_indices = single_topic.argsort()[-10:]

In [24]:
for index in top_word_indices:
    print(cv.get_feature_names_out()[index])

don
way
time
going
really
know
think
just
people
like


These look like business articles perhaps... Let's confirm by using .transform() on our vectorized articles to attach a label number. But first, let's view all the 10 topics found.

In [25]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['new', 'lot', 'make', 'things', 've', 'don', 'way', 'time', 'going', 'really', 'know', 'think', 'just', 'people', 'like']


THE TOP 15 WORDS FOR TOPIC #1
['presidential', 'republicans', 'comey', 'administration', 'obama', 'new', 'election', 'republican', 'white', 'donald', 'house', 'campaign', 'said', 'president', 'trump']


THE TOP 15 WORDS FOR TOPIC #2
['government', 'say', 'city', 'day', 'university', 'year', 'water', 'food', 'time', 'just', 'new', 'years', 'like', 'people', 'says']


THE TOP 15 WORDS FOR TOPIC #3
['according', 'reports', 'news', 'department', 'new', 'law', 'time', 'government', 'house', 'npr', 'court', 'told', 'president', 'police', 'said']


THE TOP 15 WORDS FOR TOPIC #4
['country', 'election', 'new', 'states', 'vote', 'party', 'obama', 'democratic', 'voters', 'percent', 'campaign', 'hillary', 'state', 'sanders', 'clinton']


THE TOP 15 WORDS FOR TOPIC #5
['new', 'percent', 'year', 'parents', 'private', 'kids', 'children', 'student',

### Attaching Discovered Topic Labels to Original Articles

In [26]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [27]:
dtm.shape

(11992, 54777)

In [28]:
len(npr)

11992

In [29]:
topic_results = LDA.transform(dtm)

In [30]:
topic_results.shape

(11992, 7)

In [31]:
topic_results[0]

array([0.05367521, 0.88498002, 0.00660074, 0.24558176, 0.18697022,
       0.01331588, 0.        ])

In [32]:
topic_results[0].round(2)

array([0.05, 0.88, 0.01, 0.25, 0.19, 0.01, 0.  ])

In [33]:
topic_results[0].argmax()

1

This means that our model thinks that the first article belongs to topic #1.

### Combining with Original Data

In [34]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [35]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 2], dtype=int64)

In [36]:
npr['Topic'] = topic_results.argmax(axis=1)

In [37]:
npr.head(20)

Article  Topic
0   In the Washington of 2016, even when the polic...      1
1     Donald Trump has used Twitter  —   his prefe...      1
2     Donald Trump is unabashedly praising Russian...      1
3   Updated at 2:50 p. m. ET, Russian President Vl...      3
4   From photography, illustration and video, to d...      5
5   I did not want to join yoga class. I hated tho...      0
6   With a   who has publicly supported the debunk...      6
7   I was standing by the airport exit, debating w...      2
8   If movies were trying to be more realistic, pe...      2
9   Eighteen years ago, on New Year’s Eve, David F...      2
10  For years now, some of the best, wildest, most...      0
11  For years now, some of the best, wildest, most...      0
12  The Colorado River is like a giant bank accoun...      2
13  For the last installment of NPR’s holiday reci...      0
14  Being overweight can raise your blood pressure...      2
15  Who’s the YouTube star of 2016? Adele singing ...      3
16  Here’s a quick roundup of some of the   you ma...      3
17  Ben Johnston doesn’t follow the rules of music...      2
18  David Bowie, Prince and George Michael are all...      0
19  In November, the typically straitlaced Office ...      1

In [38]:
npr.shape

(11992, 2)

In [43]:
# Step 1: Topic number to topic name mapping
topic_names = {
    0: "Personal Development / Self-Reflection",
    1: "U.S. Politics and Trump Administration",
    2: "Society and Daily Life",
    3: "News & Legal Affairs",
    4: "U.S. Elections & Political Parties",
    5: "Education System",
    6: "Healthcare & Insurance"
}

# Step 2: Map topic numbers to topic names
npr["topic_name"] = npr["Topic"].map(topic_names)

# Step 3: Check updated DataFrame
npr.head()


Article  Topic  \
0  In the Washington of 2016, even when the polic...      1   
1    Donald Trump has used Twitter  —   his prefe...      1   
2    Donald Trump is unabashedly praising Russian...      1   
3  Updated at 2:50 p. m. ET, Russian President Vl...      3   
4  From photography, illustration and video, to d...      5   

                               topic_name  
0  U.S. Politics and Trump Administration  
1  U.S. Politics and Trump Administration  
2  U.S. Politics and Trump Administration  
3                    News & Legal Affairs  
4                        Education System

In [44]:
npr

Article  Topic  \
0      In the Washington of 2016, even when the polic...      1   
1        Donald Trump has used Twitter  —   his prefe...      1   
2        Donald Trump is unabashedly praising Russian...      1   
3      Updated at 2:50 p. m. ET, Russian President Vl...      3   
4      From photography, illustration and video, to d...      5   
...                                                  ...    ...   
11987  The number of law enforcement officers shot an...      3   
11988    Trump is busy these days with victory tours,...      1   
11989  It’s always interesting for the Goats and Soda...      3   
11990  The election of Donald Trump was a surprise to...      4   
11991  Voters in the English city of Sunderland did s...      2   

                                   topic_name  
0      U.S. Politics and Trump Administration  
1      U.S. Politics and Trump Administration  
2      U.S. Politics and Trump Administration  
3                        News & Legal Affairs  
4                            Education System  
...                                       ...  
11987                    News & Legal Affairs  
11988  U.S. Politics and Trump Administration  
11989                    News & Legal Affairs  
11990      U.S. Elections & Political Parties  
11991                  Society and Daily Life  

[11992 rows x 3 columns]

# NON NEGATIVE MATRIX FACTORIZATION ALGORITHMS

In [45]:
#https://scikit-learn.org/stable/modules/decomposition.html#nmf

import numpy as np
from sklearn.decomposition import NMF
X = np.array([[1, 1], [2, 1], [3, 1.2], [4, 1], [5, 0.8], [6, 1]])


In [46]:
model = NMF(n_components=2, init='random', random_state=0)


In [47]:
W = model.fit_transform(X)
H = model.components_


In [48]:
X_new = np.array([[1, 0], [1, 6.1], [1, 0], [1, 4], [3.2, 1], [0, 4]])
W_new = model.transform(X_new)

In [49]:
W

array([[0.        , 0.46880684],
       [0.55699523, 0.3894146 ],
       [1.00331638, 0.41925352],
       [1.6733999 , 0.22926926],
       [2.34349311, 0.03927954],
       [2.78981512, 0.06911798]])

In [50]:
H

array([[2.09783018, 0.30560234],
       [2.13443044, 2.13171694]])

In [51]:
X_new

array([[1. , 0. ],
       [1. , 6.1],
       [1. , 0. ],
       [1. , 4. ],
       [3.2, 1. ],
       [0. , 4. ]])

In [52]:
W_new

array([[0.46677737, 0.        ],
       [0.        , 1.66350401],
       [0.46677737, 0.        ],
       [0.        , 1.17156989],
       [1.2277735 , 0.29280011],
       [0.        , 0.93701736]])

Using scikit-learn. We use the built-in 20 newsgroups dataset and see what topics are generated.

In [53]:
#https://scikit-learn.org/0.19/datasets/twenty_newsgroups.html
import numpy as np
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

In [ ]:
data= fetch_20newsgroups(remove=('headers', 'footers', 'quotes')).data

In [ ]:
# convert the text to a tf-idf weighted term-document matrix
 
vectorizer = TfidfVectorizer(max_features=2000, min_df=10, stop_words='english')
X = vectorizer.fit_transform(data)
idx_to_word = np.array(vectorizer.get_feature_names())
 
# apply NMF
 
nmf = NMF(n_components=20, solver="mu")
W = nmf.fit_transform(X)
H = nmf.components_
 
# print the topics
 
for i, topic in enumerate(H):
    print("Topic {}: {}".format(i + 1, ",".join([str(x) for x in idx_to_word[topic.argsort()[-10:]]])))